spring:
  application:
    name: client01
  redis:
    single: 192.168.183.9:6378
    cluster:
      nodes: 192.168.183.9:6378
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: 3000
    timeout: 3000
    password:

confserver:
  confs:
    confserverurl: http://localhost:8000 #配置中心服务地址
    currentConfVersion: application-20180903.properties #需要同步配置的版本 也是订阅channel名
server:
  port: 8002